### ISSUE TITLE
Trampoline allocation error

### ISSUE THREAD

**Issue by m0nsterJ** [HvH-gg/CS2-Essentials#17]
first time trying to use the plugin and this occurred:
`15:53:07 [EROR] (cssharp:PluginManager) Failed to load plugin from C:\Users\Administrator\Documents\cs2\game\csgo\addons\counterstrikesharp\plugins\CS2-Essentials\CS2-Essentials.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1064
   at hvhgg_essentials.Plugin.Load(Boolean hotReload) in /home/runner/work/CS2-Essentials/CS2-Essentials/CS2-Essentials/Plugin.cs:line 103
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93`

**Comment by mrc4tt** [comment]
Update the plugin / gamedata. :-)

**Comment by m0nsterJ** [comment]
Okay the above error disappeared but I'm now facing this one, which makes weapon restrictions not work:
`[HvH.gg] Register weapon restriction listeners
[Info] - Trampoline - Bounds of relative addresses accessed [0xffffffffffffffff, 0x7812850a6d20]
[Info] - Trampoline - Attempting to allocate trampoline within +-2GB range of [0xffffffffffffffff, 0x7812850a6d20] with a trampoline maximum size of 1000
[Warning] - Trampoline - Could not allocate trampoline within desired range. We currently can't relocate rip-relative instructions in this case!
[Error] - Trampoline - The trampoline could not be allocated withing +-2GB range. The instructions at the hook address do contain rip-relative memory access. Relocating those is not supported when the trampoline is not in +-2GB range!
[Error] - Detour - Failed to allocate trampoline`

and yes there is sufficient memory on the ubuntu server.
